# Module 6 Assignment: Functions and Modular Programming
# TechRetail Sales Analysis System

# Welcome message
print("=" * 60)
print("TECHRETAIL SALES ANALYSIS SYSTEM")
print("=" * 60)

# Sample quarterly sales data
# Format: [product_name, category, price, quantity_sold, employee_id]
sales_data = [
    ["Smartphone Pro", "Phones", 899.99, 15, "E101"],
    ["Laptop Ultra", "Computers", 1299.99, 10, "E105"],
    ["Wireless Earbuds", "Audio", 149.99, 30, "E101"],
    ["Smart Watch", "Wearables", 249.99, 12, "E102"],
    ["Gaming Console", "Gaming", 499.99, 8, "E103"],
    ["Bluetooth Speaker", "Audio", 79.99, 25, "E102"],
    ["Tablet Lite", "Computers", 399.99, 18, "E104"],
    ["Digital Camera", "Cameras", 599.99, 5, "E105"],
    ["VR Headset", "Gaming", 299.99, 7, "E103"],
    ["Fitness Tracker", "Wearables", 129.99, 22, "E104"],
    ["Smartphone Plus", "Phones", 699.99, 20, "E101"],
    ["Laptop Basic", "Computers", 899.99, 14, "E105"],
]

# Employee information
# Format: {employee_id: [name, commission_rate]}
employees = {
    "E101": ["Alex Johnson", 0.05],
    "E102": ["Sarah Williams", 0.045],
    "E103": ["James Brown", 0.04],
    "E104": ["Lisa Davis", 0.05],
    "E105": ["Michael Wilson", 0.055],
}


def calculate_total_sales():
    """Calculate total revenue from all sales transactions.

    Returns:
        float: Sum of (price * quantity) for all rows in ``sales_data``.
    """
    return sum(price * quantity for _, _, price, quantity, _ in sales_data)


def calculate_category_sales(category):
    """Calculate total revenue for a specific category.

    Args:
        category (str): Category name to filter on (e.g., ``"Phones"``).

    Returns:
        float: Revenue generated by matching category rows.
    """
    return sum(
        price * quantity
        for _, item_category, price, quantity, _ in sales_data
        if item_category == category
    )


def find_best_selling_product():
    """Identify the product with the highest total revenue.

    Returns:
        tuple[str, float]: ``(product_name, total_revenue)`` for the top product.
    """
    product_revenues = {}
    for product_name, _, price, quantity, _ in sales_data:
        product_revenues[product_name] = product_revenues.get(product_name, 0) + (
            price * quantity
        )

    best_product = max(product_revenues, key=product_revenues.get)
    return best_product, product_revenues[best_product]


def calculate_employee_commission(employee_id):
    """Calculate commission earned by one employee.

    Args:
        employee_id (str): Employee identifier (e.g., ``"E101"``).

    Returns:
        float: Employee commission based on their sales total and commission rate.
    """
    if employee_id not in employees:
        return 0.0

    _, commission_rate = employees[employee_id]
    employee_sales = sum(
        price * quantity
        for _, _, price, quantity, sale_employee_id in sales_data
        if sale_employee_id == employee_id
    )
    return employee_sales * commission_rate


def calculate_total_commission():
    """Calculate total commissions for all employees.

    Returns:
        float: Sum of commission for every employee in ``employees``.
    """
    return sum(calculate_employee_commission(employee_id) for employee_id in employees)


def generate_sales_summary(include_categories=True):
    """Build a formatted sales summary report.

    Args:
        include_categories (bool, optional): Include category breakdown when True.
            Defaults to True.

    Returns:
        str: Multi-line report describing totals and key metrics.
    """
    total_sales = calculate_total_sales()
    average_sale_price = calculate_average_sale_price()
    best_product, best_product_revenue = find_best_selling_product()

    report_lines = [
        "TechRetail Quarterly Sales Summary",
        "-" * 36,
        f"Total Revenue: ${total_sales:,.2f}",
        f"Average Unit Price: ${average_sale_price:,.2f}",
        f"Best-Selling Product: {best_product} (${best_product_revenue:,.2f})",
    ]

    if include_categories:
        report_lines.append("\nCategory Breakdown:")
        categories = sorted({row[1] for row in sales_data})
        for category in categories:
            report_lines.append(
                f"- {category}: ${calculate_category_sales(category):,.2f}"
            )

    report_lines.append(f"\nTotal Commission Expense: ${calculate_total_commission():,.2f}")
    return "\n".join(report_lines)


def generate_employee_report():
    """Generate a formatted employee performance report.

    Returns:
        str: Multi-line report with employee sales and commissions.
    """
    lines = ["Employee Performance Report", "-" * 28]

    for employee_id, (name, rate) in employees.items():
        total_sales = sum(
            price * quantity
            for _, _, price, quantity, sale_employee_id in sales_data
            if sale_employee_id == employee_id
        )
        commission = calculate_employee_commission(employee_id)
        lines.append(
            f"{name} ({employee_id}) | Sales: ${total_sales:,.2f} "
            f"| Rate: {rate:.1%} | Commission: ${commission:,.2f}"
        )

    return "\n".join(lines)


def get_products_by_category(category):
    """Return all products that belong to one category.

    Args:
        category (str): Category used to filter products.

    Returns:
        list: List of product names in the selected category.
    """
    return [product_name for product_name, item_category, *_ in sales_data if item_category == category]


def calculate_average_sale_price():
    """Calculate average unit price across all transactions.

    Returns:
        float: Arithmetic mean of the product prices in ``sales_data``.
    """
    if not sales_data:
        return 0.0
    return sum(price for _, _, price, _, _ in sales_data) / len(sales_data)


def main():
    """Run the TechRetail quarterly sales analysis workflow."""
    print("\nTECHRETAIL QUARTERLY SALES ANALYSIS")
    print("-" * 40)

    print("\nTOTAL QUARTERLY SALES:")
    print(f"${calculate_total_sales():,.2f}")

    print("\nSALES BY CATEGORY:")
    categories = ["Phones", "Computers", "Audio", "Wearables", "Gaming", "Cameras"]
    for category in categories:
        print(f"{category}: ${calculate_category_sales(category):,.2f}")

    print("\nBEST-SELLING PRODUCT:")
    best_product, best_revenue = find_best_selling_product()
    print(f"{best_product} - ${best_revenue:,.2f}")

    print("\nEMPLOYEE COMMISSIONS:")
    for employee_id, (name, _) in employees.items():
        print(f"{name}: ${calculate_employee_commission(employee_id):,.2f}")

    print("\nQUARTERLY SALES SUMMARY REPORT:")
    print(generate_sales_summary())

    print("\nEMPLOYEE PERFORMANCE REPORT:")
    print(generate_employee_report())


if __name__ == "__main__":
    main()